name: Deploy to Hugging Face

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        lfs: true

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install huggingface_hub

    - name: Authenticate with Hugging Face
      env:
        HUGGINGFACE_TOKEN: ${{ secrets.HUGGINGFACE_TOKEN }}
      run: |
        huggingface-cli login --token $HUGGINGFACE_TOKEN

    - name: Push to Hugging Face
      run: |
        git remote add space https://huggingface.co/spaces/your_username/your_space_name
        git push --force space main
